//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.LigneCommandes = new HashSet<LigneCommande>();
        }

        public Commande(int numCmd, string dateCmd, string idClient, AspNetUser aspNetUser, ICollection<LigneCommande> ligneCommandes)
        {
            this.numCmd = numCmd;
            this.dateCmd = dateCmd;
            this.idClient = idClient;
            AspNetUser = aspNetUser;
            LigneCommandes = ligneCommandes;
        }

        public int numCmd { get; set; }
        public string dateCmd { get; set; }
        public string idClient { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneCommande> LigneCommandes { get; set; }
    }
}
