//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LigneCommande
    {
        public LigneCommande(int numLigne, int? qteArticle, double? totalPrice, int? numCmd, int? numArticle, Article article, Commande commande)
        {
            this.numLigne = numLigne;
            QteArticle = qteArticle;
            this.totalPrice = totalPrice;
            this.numCmd = numCmd;
            this.numArticle = numArticle;
            Article = article;
            Commande = commande;
        }
        [Key]
        public int numLigne { get; set; }
        public Nullable<int> QteArticle { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public Nullable<int> numCmd { get; set; }
        public Nullable<int> numArticle { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
