//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class LigneCommande
    {
        public LigneCommande()
        {
            this.Commande = new Commande();
        }

        public int numLigne { get; set; }
        public Nullable<int> QteArticle { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public Nullable<int> numCmd { get; set; }
        public Nullable<int> numArticle { get; set; }

        [JsonIgnore]
        public virtual Article Article { get; set; }
        [JsonIgnore]
        public virtual Commande Commande { get; set; }
    }
}
