//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneCommande
    {
        public int numLigne { get; set; }
        public Nullable<int> QteArticle { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public Nullable<int> numCmd { get; set; }
        public Nullable<int> numArticle { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
